### ISSUE TITLE
missing words

### ISSUE THREAD

**Issue by acrofales** [mwiens91/english-words-py#2]
I tried to use this, as it looks very easy. However, there are very many words missing. I am not sure how the list is compiled, but I noticed that it doesn't have conjugated verbs or plural forms of nouns. That is okay, but it means it isn't a list of English words, but rather a dictionary. However, even after that, it contains far fewer words than nltk's corpus of words. One word n particular that I found it was missing is "early". A "simple" corpus of English words seems like a very good idea, however it seems like this needs more work in its compilation.

```
>>> from english_words import english_words_lower_alpha_set as wds
>>> "early" in wds
False
```

**Comment by mwiens91** [comment]
Sorry for the late response.

I agree, this word list is *quite* non-exhaustive and probably doesn't fit many use cases because of this. I'm not sure how the list is compiled either, I just took it from [here](https://svnweb.freebsd.org/csrg/share/dict/) (and I've credited this in the readme).

If you're aware of a better list of words I can use, let me know and this can definitely be expanded.

**Comment by cva** [comment]
Have you considered using `web2` also available in the FreeBSD repo?

https://svnweb.freebsd.org/base/head/share/dict/

**Comment by fresh4** [comment]
@mwiens91 I wanna second @cva 's suggestion, `web2` has almost 4 times as many words and has been better for my use case in cases where this library couldn't find a word.

**Comment by mwiens91** [comment]
Thanks for posting here. I meant to look into @cva's suggestion, but life happened and eventually forgot. 

I would say that we should just replace the word list I sourced originally with `web2`, but given that in your PR you mention that `web2` lacks some words that the original list has, maybe it makes sense to keep both.

What I'm thinking of doing is writing some function `get_english_words_set` that takes in a list of available words list you want to combine (the original and `web2` being two of them), and then returns the set of the combined words lists.

So you'd call it like

```python
>>> get_english_words_set(["web2", "hypothetical_word_list_1", "hypothetical_word_list_2", ...])
```

and this would return the words from `web2`, `hypothetical_word_list1`, etc.


I'll have a look to see if there are other good words lists out there besides the one we already have and `web2`.

**Comment by fresh4** [comment]
It's no worries! I've been using this library a bit, so I'm just glad I could help in some way. Hope things are okay.

I think it's definitely reasonable to eventually combine the two lists, putting words from the old list into the new one where those words don't already exist. We'd just need to make sure comparisons aren't case sensitive, and likely a few other cases to prevent duplicates I think. But this way you could just combine as many lists as you'd like and it would only improve your dataset.

**Comment by mwiens91** [comment]
@fresh4 Took me ages to get back to this, but I've rewritten this package more or less how I outlined above in this issue. I've added all words found in the GCIDE dictionary as a word list, and now you can combine word lists. There's also structure in place to add new word lists. There are still missing words, but this can be helped by adding more word lists we can combine.

It's not perfect, and there will be scaling issues if we add too many word lists or options, but I think overall it's an improvement for now. I've done a fair amount of testing so hopefully there aren't too many bugs.

**Comment by fresh4** [comment]
@mwiens91 hey, meant to get back to this earlier, but this is awesome! Definitely an improvement.
