### ISSUE TITLE
alpha + lower doesn't work

### ISSUE THREAD

**Issue by Morilli** [mwiens91/english-words-py#7]
Hey, I've been using this package for brute force purposes and just now by chance caught the fact that specifying `alpha` + `lower` options together doesn't actually work, and just applies the `alpha` option.

The cause seems to be this line: https://github.com/mwiens91/english-words-py/blob/666bcb949fd1236f3339ae7e1285e202c699a621/english_words/__init__.py#L26
which should probably be a normal `if` instead. For now, I'll manually `lower()` the entire set, but I'd appreciate if you could fix this.

**Comment by mwiens91** [comment]
Thanks for raising this issue. Should be fixed in 94f0794.
